### ISSUE TITLE
Fisheye Cameras/Actioncams dont work correctly

### ISSUE THREAD

**Issue by Thrillerninja** [ju1ce/April-Tag-VR-FullBody-Tracker#11]
When trying to use a actioncam, the trackers are in the wrong distance to the camera. The scaling of distance to the camera is broken, so if you are close to the camera, the trackers are near you, but if you are a bit away, the trackers are way behind you

**Comment by ju1ce** [comment]
A new release has just been published with updated calibration, where you can see how well calibrated a camera is while calibrating. Could you try it now and see if it fixed anything?

How it works now: the color of the dots represent the reprojection error. Purple = good, yellow = bad. The grid represents how certain the calibration is, so you want it to be as stationary as you can

When calibrating camera, try to move it as close to the pattern as you can.

**Comment by Thrillerninja** [comment]
It works much better now. Thank you
