### ISSUE TITLE
SteamVR seems to be confusing a tracker with my controller

### ISSUE THREAD

**Issue by ZerpZerp** [ju1ce/April-Tag-VR-FullBody-Tracker#15]
![20210709140203_1](https://user-images.githubusercontent.com/83445993/125131195-8fbf8200-e0bf-11eb-9570-991d938d66a1.jpg)

And my character has the T-Pose animation. What am I doing wrong here?

**Comment by ju1ce** [comment]
SteamVR sometimes assumes the first moving tracked object to be a controller. So, if you press 6. Start, which spawns trackers, before putting on your headset and using the actual controllers, they sometimes switch places. Make sure you always go into vr, check your controllers are working, and then press 6. Start through the vr virtual desktop.

Sometimes it still happens even if you do everything right, though, in which case just restart SteamVR.

As for the T-Pose, you have to align yourself to your avatar then press both triggers to calibrate FBT. You cant do that if your controller gets switched, though.

**Comment by ZerpZerp** [comment]
Ah, I will try that. I did find "Manage trackers" but that just made both of my controllers not do anything. Will try that suggestion
