### ISSUE TITLE
360 instructions

### ISSUE THREAD

**Issue by tlhonmey** [ju1ce/April-Tag-VR-FullBody-Tracker#16]
So in other places talking about this project I've seen it mentioned that it can be set up to do 360 degree tracking instead of just 180.  But your setup guide doesn't offer a lot of hints about how to do it...

Can I just generate more tags and make the trackers into octagons or similar?  I would assume that's the reason for having such a large range assigned to each tracker...  Or does it require a second camera?  I can likely fiddle out the details if I can get an idea of where to start...

Assuming it just takes additional tags, then personally I can probably handle chasing down through the subrepos to find more tags (the pre-generated tags from the AprilTag project are 9x9px and need a bit of scaling and fitting onto standard pages...) Would you like the results of that work posted as something for other users?

**Comment by ju1ce** [comment]
Hello!

Sorry for the confusion, the setup guide may be a bit outdated by now, but I am working on a better one! Most of the updates were shared through the discord server - any instructions for the beta will be found there until i rework the github instructions, so I would suggest you join it :)

Yes, you can get more tags in the official AprilTags repo, but I do include the additional 2 markers you need for the backside in the download, inside the "images to print" folder. Examples of how trackers like that look like can also be found in the discord, in the #user-examples channel, you can look around there for ideas on how to put that together. You can also share your results there, or anywhere else you would like, i always enjoy seeing how other got this working.

If you need any help, feel free to ask. Some parts of setup, such as opening a webcam properly and setting exposure, can be a weird process that isnt well documented yet...
