### ISSUE TITLE
Doesn't recognise Kinect V2 (XBox One) sensor camera as webcam

### ISSUE THREAD

**Issue by Pyrofer** [ju1ce/April-Tag-VR-FullBody-Tracker#21]
I can use my Kinect colour camera as a webcam in most applications, it's a nice fullHD res sensor and should be well suited for tracking.
My other camera worked but nothing would make the Kinect sensor work.
To Clarify. I got an image, but when doing "calibrate camera" using the full sheet, it did not detect or draw any dots. Calibrate tags also never detected the tags.

**Comment by ju1ce** [comment]
Is the image mirrored? That could cause the problem.
Can you unmirror the kinect in its software?

**Comment by Pyrofer** [comment]
It is indeed mirrored!
I can't flip it in any other software, when I tick the "show camera settings" box in params, nothing happens.
This really needs a mirror option for each axis in the settings.
