### ISSUE TITLE
instant crash when trying OBS Virtual Cam

### ISSUE THREAD

**Issue by Nanolocity** [ju1ce/April-Tag-VR-FullBody-Tracker#22]
I have two cameras installed; a facerig virtual cam and I tried to use OBS's Virtual cam but it instantly crashes the program when I try with no error message. if I try a higher number it throws an error that there aren't this many cameras

**Comment by Nanolocity** [comment]
And yes, the camera works with other programs like Discord

**Comment by Nanolocity** [comment]
I tried another virtual cam, I think it just doesn't like virtual cameras because the new one crashed as well

**Comment by ju1ce** [comment]
OBS built in virtual camera doesnt work with att for some reason, you need the virtualcam plugin: https://obsproject.com/forum/resources/obs-virtualcam.949/

Its weird that it would crash though. Try Camera API of 0 and 700, try to set the resolution correctly, and try diffrent ids on this virtual camera as well.

If i had to guess, the facerig virtual cam causes a crash on id 0, and OBS virtual camera refuses to open on id 1. The virtualcam plugin will probably be on id 2 then.
