### ISSUE TITLE
Show what camera is being used on titlebar [Request]

### ISSUE THREAD

**Issue by LosWheatleynDew** [ju1ce/April-Tag-VR-FullBody-Tracker#23]
Add custom title or text in the app to show what camera is being used for multi camera setups

Its kinda confusing to find which application belongs to which camera so it would be nice to have either a title showing what camera its using or text on the application showing what camera the app is using.
I kinda like it custom bc i use 2 PSeye cameras and i could name them differently

**Comment by LosWheatleynDew** [comment]
Nevermind i did it myself

**Comment by ju1ce** [comment]
based
