### ISSUE TITLE
All the trackers seem to be out of place

### ISSUE THREAD

**Issue by Evangeder** [ju1ce/April-Tag-VR-FullBody-Tracker#32]
Hey! I recently made a waist and leg trackers for AprilTag.

![20220315_214726](https://user-images.githubusercontent.com/51864869/158549763-54fa8efe-7491-48b7-bdc7-81ec8cd64475.jpg)

Once i calibrated the cam (good calibration as far as i see) and the trackers i hopped onto SteamVR.

Trackers seem to be recognized correctly (left leg is indeed a left leg, etc), but all of them seem to be way above me, like 1.5 to 2 meters above me.

There should be a way to calibrate XYZ offsets for the trackers because of that, because i honestly have no idea what should i do about it. I tried repositioning the camera, restarting software, recalibrating everything (even room in SteamVR). No luck.

Anyone knows a fix/workaround for that?

**Comment by ju1ce** [comment]
after the camera is in position, you should be able to use grip on your left controller to rotate it in the correct direction. Rotating the camera also has the effect of moving the trackers, so you should be able to move them in position with that.

**Comment by Evangeder** [comment]
Oh, i just found out that you can reposition the camera in VR view, that solved the problem.
Sorry and thanks!
