### ISSUE TITLE
Whole computer is lagging since I downloaded this exact thing

### ISSUE THREAD

**Issue by Lex0planet** [ju1ce/April-Tag-VR-FullBody-Tracker#51]
Hi, I'm not used to github markdown so I don't know if It's the right way to submit issues, but since I downloaded the software, it started when using it as it lagged down my VR a lot, then it started lagging out other things such as discord or even my web browser, and even after deleting it the lag still goes on.
I don't know if it's a know issue or just me ?

**Comment by ju1ce** [comment]
Thats weird... did it happen only once or every time? It is possible that there was a memory leak somewhere, but I havent heard of such an issue yet

**Comment by Lex0planet** [comment]
Well I am terribly sorry, looked like a heat wave just passed over my country when I downloaded it, turns out it was a computer ventilation issue and my CPU was litterally melting, terribly sorry again
