### ISSUE TITLE
not responding

### ISSUE THREAD

**Issue by ShadedHemlock** [ju1ce/April-Tag-VR-FullBody-Tracker#54]
I have been trying to set this up for a few days now and have uninstalled and reinstalled everything once but when I get to the step to preview the camera and set up the trackers the program stops responding and forces me to close it I don't know if this is a problem on my end and have been working to figure out if it is but would like to hear opinions and /or likely solutions. Thank you

**Comment by ju1ce** [comment]
Some USB cameras take a very long time to open on default settings, sometimes up to a minute, so its possible you just have to wait for a bit longer. Or, set the Camera API Preference parameter to 700, that can often speed things up, if supported by the camera.
