### ISSUE TITLE
Could not connect to SteamVR driver.

### ISSUE THREAD

**Issue by SummerArtz** [ju1ce/April-Tag-VR-FullBody-Tracker#97]
![image](https://user-images.githubusercontent.com/75969241/190895580-8b9ca8d8-08bf-4daa-a360-45eb21b8836d.png)
When i try to connect this error pops up.

**Comment by ju1ce** [comment]
First, check steamvr settings -> startup -> addons, make sure that apriltagtrackers is listed and enabled. SteamVR sometimes likes to disable drivers for no reason, and then you have to enable them manualy.

If the driver is not listed under addons, something seemed to have gone wrong during the driver install. Run the install_driver.bat and screenshot the output here.

If the driver is listed and enabled, but you still get the above error, try to run ApriltagTrackers.exe as administrator.

If none of the above worked, please send me the vrserver.txt file. Should be in steam/logs. It usualy contains some information on why the driver fails to load.
